version: '{build}'
skip_tags: true
image: Visual Studio 2019 Preview
configuration: Release
build_script:
- ps: ./Build.ps1
test: off
artifacts:
- path: artifacts/Superpower.*.nupkg
deploy:
- provider: NuGet
  api_key:
    secure: Xi+qouQ6+cOJ85PMOQKEGy+MC1EKyYJCoF2YfuE9Rcj6lvNtm08TIZllTJCqId+M
  skip_symbols: true
  on:
    branch: /^(master|dev)$/
- provider: GitHub
  auth_token:
    secure: hX+cZmW+9BCXy7vyH8myWsYdtQHyzzil9K5yvjJv7dK9XmyrGYYDj/DPzMqsXSjo
  artifact: /Superpower.*\.nupkg/
  tag: v$(appveyor_build_version)
  on:
    branch: master
